### ISSUE TITLE
Show package size on wapm.io

### ISSUE THREAD

**Issue by MaxGraey** [wasmerio/wapm-cli#111]
### Proposed solution

It will be great if each package on wapm.io reflect its size like:

![sizes](https://user-images.githubusercontent.com/1301959/57976064-607dc080-79e0-11e9-868d-db013bf72db1.jpg)

**Comment by syrusakbary** [comment]
I think that's a great idea! 💯

Will implement it soon

**Comment by syrusakbary** [comment]
And... the changes are live in [wapm.io](https://wapm.io/)!

<img width="973" alt="Screen Shot 2019-05-20 at 2 12 20 PM" src="https://user-images.githubusercontent.com/188257/58052388-8ce12c00-7b09-11e9-92a6-8348e04f64ca.png">

We also added the info on the package page :)

Thanks for proposing the idea!
Let us know if you have more suggestions!

**Comment by MaxGraey** [comment]
Thanks! 👍
