### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by mmacedoeu** [wasmerio/wapm-cli#134]
Thanks for proposing a new feature!

### Motivation

Most people work behind corporate proxy

### Proposed solution

Expose use of reqwest proxy into cli

**Comment by zicklag** [comment]
I would also greatly appreciate this feature. It would be great if it would read the `http_proxy` environment variable, and allow for setting in `wapm config` as well.

**Comment by MarkMcCaskey** [comment]
Thanks!  We always appreciate hearing about what our users need -- that doesn't look too hard to implement!

I'll add it to my todo list

**Comment by MarkMcCaskey** [comment]
Hello!  I made a quick PR today but haven't been able to test it with a proxy yet.

You can use `wapm config set proxy.url "your-proxy-url"` or set `WAPM_PROXY_URL`

If either of you have time, let me know if this is sufficient and if it works!  I'll try to find a proxy I can use to test tomorrow to verify it works
