### ISSUE TITLE
Error: Failed to open logging file in WASMER_DIR: error type: NotFound

### ISSUE THREAD

**Issue by alexreg** [wasmerio/wapm-cli#170]
I get this when I try to run any `wapm` command, it seems. (Specifically, I am trying `wapm login` and `wapm init` for now.) What is this about?

**Comment by syrusakbary** [comment]
Hi @alexreg,

How did you installed WAPM... via Wasmer? (`curl https://get.wasmer.io -sSfL | sh`)

Can you run the following and write here the output?

```
which wasmer
which wapm
```

Thanks!

**Comment by alexreg** [comment]
@syrusakbary Hi. I installed both through macOS Homebrew (I just wrote a formula for the latter which basically builds from source and installs using `cargo install`, in the standard Homebrew way). Wasmer is also installed via Homebrew, (existing formula).

```
$ which wasmer
/usr/local/bin/wasmer
$ which wapm
/usr/local/bin/wapm
```

**Comment by syrusakbary** [comment]
It seems we are missing directory creation and env vars assignment when we are installing from the Homebrew formula.

Adding @Hywan to the thread :).

Note: when someone instals Wasmer from source, not only the binaries are installed but also:
1. A directory for Wasmer is created (to save there some cache files and configuration)
2. Some new env vars are created:
     * `WASMER_DIR` (pointing to the directory mentioned in 1)
     * `WASMER_CACHE_DIR` (`WASMER_CACHE_DIR=$WASMER_DIR/cache`)
     * `PATH` pointing to `PATH=$WASMER_DIR/bin:$PATH:$WASMER_DIR/globals/wapm_packages/.bin`
3. That's it!

It seems we would need to replicate this on the main [Wasmer homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/wasmer.rb)?

> I just wrote a formula for the latter which basically builds from source and installs using cargo install, in the standard Homebrew way
That's awesome! Would be great to add the wapm formula into Homebrew main repo

**Comment by alexreg** [comment]
Ah, that sounds very much like it is the problem!

Here is my PR for wapm: https://github.com/Homebrew/homebrew-core/pull/50556

It actually doesn't rely on those env vars being set correctly, since it wants to use a custom `WASMER_DIR` for testing anyway. :-)

But yes, I think we need to fix the Wasmer formula regardless...

**Comment by BernhardRode** [comment]
Having the same issue here on latest OS X:

```
➜  ~  curl https://get.wasmer.io -sSfL | sh
Welcome to the Wasmer bash installer!

               ww
               wwwww
        ww     wwwwww  w
        wwwww      wwwwwwwww
ww      wwwwww  w     wwwwwww
wwwww      wwwwwwwwww   wwwww
wwwwww  w      wwwwwww  wwwww
wwwwwwwwwwwwww   wwwww  wwwww
wwwwwwwwwwwwwww  wwwww  wwwww
wwwwwwwwwwwwwww  wwwww  wwwww
wwwwwwwwwwwwwww  wwwww  wwwww
wwwwwwwwwwwwwww  wwwww   wwww
wwwwwwwwwwwwwww  wwwww
   wwwwwwwwwwww   wwww
       wwwwwwww
           wwww

downloading: wasmer-darwin-amd64
Latest release: 2.2.0-rc2
Downloading archive from https://github.com/wasmerio/wasmer/releases/download/2.2.0-rc2/wasmer-darwin-amd64.tar.gz
######################################################################## 100.0%
installing: /Users/user/.wasmer
Updating bash profile /Users/user/.zshrc
we've added the following to your /Users/user/.zshrc
If you have a different profile please add the following:

# Wasmer
export WASMER_DIR="/Users/user/.wasmer"
[ -s "$WASMER_DIR/wasmer.sh" ] && source "$WASMER_DIR/wasmer.sh"
check: wasmer 2.2.0-rc2 installed successfully ✓
wasmer & wapm will be available the next time you open the terminal.
If you want to have the commands available now please execute:

source /Users/user/.wasmer/wasmer.sh
➜  ~  source /Users/user/.wasmer/wasmer.sh
➜  ~  which wasmer
/Users/user/.wasmer/bin/wasmer
➜  ~  which wapm  
/Users/user/.wasmer/bin/wapm
➜  ~  wapm install cowsay
[INFO] Installing syrusakbary/cowsay@0.2.0
Error: Failed to install packages. Could not install package(s). There was an IO error creating the wapm_packages directory for package "syrusakbary/cowsay 0.2.0". No such file or directory (os error 2)
➜  ~  ls -R ~/.wasmer
ATTRIBUTIONS LICENSE      bin          globals      include      lib          wapm.log     wapm.sqlite  wasmer.sh

/Users/user/.wasmer/bin:
wapm            wasmer          wasmer-headless wax

/Users/user/.wasmer/globals:
wapm_packages

/Users/user/.wasmer/globals/wapm_packages:
syrusakbary

/Users/user/.wasmer/globals/wapm_packages/syrusakbary:
cowsay@0.2.0

/Users/user/.wasmer/globals/wapm_packages/syrusakbary/cowsay@0.2.0:

/Users/user/.wasmer/include:
README.md     wasm.h        wasmer.h      wasmer_wasm.h

/Users/user/.wasmer/lib:
libwasmer.a     libwasmer.dylib
```

So it created some folders, but did not manage to put the cowsay.wasm file into the correct folder.
