### ISSUE TITLE
Overlap between docs

### ISSUE THREAD

**Issue by alexreg** [wasmerio/wapm-cli#173]
I see there is quite a lot of overlap between https://wapm.io/help/guide (and https://wapm.io/help/install) on one hand, and https://docs.wasmer.io/ecosystem/wapm (and its subpages) on the other. Is this distinction intentional? I guess the duplication of mainly equivalent content in a slightly different form is a little confusing, though obviously not too much! Anyway, it seems less than ideal.

**Comment by syrusakbary** [comment]
Thanks for opening this!
We just updated the wapm.io website to link to all the docs under https://docs.wasmer.io/ecosystem/wapm based on your feeback 🙂

**Comment by alexreg** [comment]
@syrusakbary Sure. I still see https://wapm.io/help/guide as a separate page though... what do you mean?
