### ISSUE TITLE
Request: Publish package from CI environment to wapm.io

### ISSUE THREAD

**Issue by KSXGitHub** [wasmerio/wapm-cli#193]
### Motivation

I want to publish my package automatically from CI, but wapm authentication model does not make it easy:
* `wapm login` provides no option to login without user interaction.
* wapm.io does not provide auth token, meaning that I have to save my password in the CI. This may pose a security threat.

### Proposed solution

Provide a way to publish package using auth token.

**Comment by Michael-F-Bryan** [comment]
This should be possible now because the `wapm` CLI accepts tokens generated on [wapm.io](https://wapm.io). If you are using GitHub Actions, the [`wasmerio/wapm-publish`](https://github.com/wasmerio/wapm-publish) action will take care of the authenticating and publishing for you.
