### ISSUE TITLE
cargo-wapm

### ISSUE THREAD

**Issue by Michael-F-Bryan** [wasmerio/wapm-cli#223]
### Motivation

Publishing a Rust crate to WAPM is currently a manual task where you need to modify your `manifest.toml` then make sure you compile in release mode and move all files to be published into the right place. 

### Proposed solution

Create a `cargo wapm` command which will automatically publish a Rust crate to WAPM.

As part of the publishing process, it would 

- Offer to bump version numbers and add a git tag (I'm on the fence for this one because I'll typically just use [`cargo release`](https://github.com/crate-ci/cargo-release))
- compile the crate in release mode
- automatically construct a `manifest.toml` based on your existing `Cargo.toml` (possibly with the help of [the metadata table](https://doc.rust-lang.org/cargo/reference/manifest.html#the-metadata-table))
- copy everything to the `target/wapm/` folder
- Publish to WAPM

I'm not sure of the semantics regarding Cargo workspaces vs packages here. It might make sense for a single Rust crate to correspond to a single WAPM package, but at the same time you might want the entire workspace to be a WAPM package and each crate gets added as a [`[[module]]`](https://docs.wasmer.io/ecosystem/wapm/manifest#module).

### Alternatives

Nothing about this process requires knowledge of WAPM internals, so it's quite feasible for users to roll their own solution. This might look like a [`cargo xtask`](https://github.com/matklad/cargo-xtask), an explicit `deploy.sh` script, or a task in your project's `Makefile`.

**Comment by syrusakbary** [comment]
This is a great idea! We'll take a look into it soon

**Comment by Michael-F-Bryan** [comment]
I've implemented this with [`Michael-F-Bryan/cargo-wapm`](https://github.com/Michael-F-Bryan/cargo-wapm).
