### ISSUE TITLE
Fails to validate / upload WebAssembly WASI module with bulks memory operations

### ISSUE THREAD

**Issue by thewtex** [wasmerio/wapm-cli#242]
With `wapm validate .` or `wapm upload`, on a WASI binary built with WASI-SDK 16 (attached), the error occurs:

```
Error: WASM file "./VTKImageIOReadImage.wasi.wasm" detected as invalid because InvalidWasm { error: "bulk memory support is not enabled (at offset 312194)" }
```

`wasm2wat` confirms the presence of the operations.

bulk memory appears to be supported by most runtimes and I would not expect it to be a blocker.

```bash
wapm -V

wapm-cli 0.5.4


rustc -V

rustc 1.53.0 (53cb7b09b 2021-06-17)
[example-bulk-memory.zip](https://github.com/wasmerio/wapm-cli/files/9043287/example-bulk-memory.zip)


```

**Comment by zicklag** [comment]
I just tried to publish my first WAPM module from a simple Rust crate and I'm also running into this. I can confirm that running it with wasmer works, if I `wasmer run my_wasm_module.wasm`.
