### ISSUE TITLE
Update Wapm config to receive "bindings"

### ISSUE THREAD

**Issue by syrusakbary** [wasmerio/wapm-cli#248]
We need to modify `wapm.toml` so the packages are able to define when they have a library with bindings.

```yaml
[package]
name = "blabla"

[module]
name = "mylib"
wit-bindings-exported = { file = "./my-lib-bindings.wit", version = "the-wit-bindgen-version" }
```

When adding bindings we should also validate them with the given version hosted in WAPM (the wit validator should live also in WAPM).

**Comment by fschutt** [comment]
This can be closed since #252 is merged.
