### ISSUE TITLE
Integrate bindings into WAPM-cli

### ISSUE THREAD

**Issue by syrusakbary** [wasmerio/wapm-cli#249]
We should support:
```
wapm install mylibrary --npm
```

Which will:
1. Fetch the library from GraphQL, and fetch the node package url from Wasmer CDN
2. Run `npm install https://registry.wapm.dev/npm/mylibrary.tar.gz`

The GraphQL backend will be able to be queried like:

```graphql
{
  getPackageVersion(name:"python/python") {
    bindings {
      npm {
        defaultInstallPackageName
      }
    }
  }
}
```

Note: This doesn't require syndication

**Comment by syrusakbary** [comment]
![Image](https://user-images.githubusercontent.com/188257/186128672-f2794520-efb1-4860-9fad-490156316d5f.png)

**Comment by Michael-F-Bryan** [comment]
This was implemented in https://github.com/wasmerio/wapm-cli/pull/262.
