### ISSUE TITLE
Publish always times out

### ISSUE THREAD

**Issue by guregu** [wasmerio/wapm-cli#264]
### Describe the bug

Publishing to WAPM (from Github Actions?) seems to always time out, despite the publish succeeding. I have not been able to reproduce locally.

Using `wasmerio/setup-wasmer@v1` action.

### Steps to reproduce

Here is my Github Actions workflow: https://github.com/guregu/trealla/blob/c5f933f1232f4917a44c4810452d98533dc5cf08/.github/workflows/build.yaml#L86-L88

I had to add the `|| echo ...` bit otherwise it would fail always.

### Expected behavior

Publish succeeds.

### Actual behavior

This error message is printed:

```
Error: error sending request for url (https://registry.wapm.io/graphql): operation timed out
```

However, the publish still works.

### Additional context

Here is a real example: https://github.com/guregu/trealla/runs/8049159280 displays the above error message but [trealla@0.1.16](https://wapm.io/guregu/trealla/tree/0.1.16) was successfully published.

**Comment by syrusakbary** [comment]
Thanks for reporting the issue. We'll investigate

**Comment by guregu** [comment]
Looks like this has been fixed (not getting errors for a while). Thanks!

**Comment by syrusakbary** [comment]
Yes, we improved the upload by doing it by chunks directly to the CDN.
Happy to see it was fully fixed on your side
