### ISSUE TITLE
can you update the crates version of wapm-cli from 0.5.1 to 0.5.6

### ISSUE THREAD

**Issue by silverhikari** [wasmerio/wapm-cli#275]
### Summary

when installing from crates.io noticed the version that avaible is now a few versions behind from both github and homebrew. so i am asking if you can update the version that is used on crates to the latest version

**Comment by syrusakbary** [comment]
Good call! Adding @fschutt to the thread

**Comment by fschutt** [comment]
Since we are unifying wasmer-cli and wapm-cli into one tool (this repo will be deprecated), I will publish to crates.io one last time when #281 is merged. After that, this repo will be archived and `0.5.6` will be the last version.
