### ISSUE TITLE
wapm install always fails with "Manifest must be a file named wapm.toml"

### ISSUE THREAD

**Issue by Michael-F-Bryan** [wasmerio/wapm-cli#293]
If you try to use the latest `master` ([c935160](https://github.com/wasmerio/wapm-cli/commit/c935160a643f41a12993933b4a11965d769d97ab)) to install a package, the installation will always fail due to an internal error.

```console
$ wapm install wasmer/wabt
Error: Failed to install packages. Could not open manifest. Could not parse manifest because Manifest must be a file named `wapm.toml`..
```

This is the issue that's been [causing our regression tests to fail](https://github.com/wasmerio/wapm-cli/actions/runs/3327134410/jobs/5501824857) on `master`.

**Comment by Michael-F-Bryan** [comment]
I believe this may be related to https://github.com/wasmerio/wasmer/issues/3247.

**Comment by fschutt** [comment]
This was fixed by https://github.com/wasmerio/wapm-cli/pull/299
