### ISSUE TITLE
The Wasmer directory is missing. Is Wasmer not installed?

### ISSUE THREAD

**Issue by svenstaro** [wasmerio/wapm-cli#58]
### Describe the bug

I packaged wapm for Arch Linux: https://aur.archlinux.org/packages/wapm/ and I believe I packaged it correctly. I also packaged wasmer: https://aur.archlinux.org/packages/wasmer

Upon running wapm I get this:

```
wapm install cowsay
Fatal Error: 
The Wasmer directory is missing. Is Wasmer not installed?
Install Wasmer at https://wasmer.io.
```

Now, I didn't get Wasmer from the normal location because I prefer compiling my packages myself and integrating them into my system. I'm not sure where I'm going wrong. My system has working and available `/usr/bin/wapm` and `/usr/bin/wasmer` binaries.

Is there anything I need to be doing during the installation of this package so that it'll work?

**Comment by MarkMcCaskey** [comment]
Hi!

Thanks for your work!

Check out the install script here: https://github.com/wasmerio/wasmer/blob/master/install.sh#L133-L134 (the lines I linked to are the ones relevant to the, perhaps poorly named in the context of wapm, `WASMER_DIR`)

From memory, I believe all it wants is a place to write its more verbose logging into a file and a config file if any of the default settings have changed.

Let me know if that doesn't work or you have any other issues!

**Comment by svenstaro** [comment]
Ok I get that but why doesn't it default to that dir if the variable is
unset like basically all other programs? I think that's a sensible thing to
do.

**Comment by gerdus** [comment]
This also happens on windows using the exe installer

**Comment by xmclark** [comment]
@gerdus this was an oversight! Our bad. If you create that `.wasmer` directory in your user directory, correct behavior should resume. I will add this as an issue to the wasmer repository because this is where we manage the creation of installers. Wapm-cli and Wasmer are bundled together.

**Comment by xmclark** [comment]
https://github.com/wasmerio/wasmer/issues/394

**Comment by svenstaro** [comment]
As a distro maintainer, should one of my packages depend on the other? They
are technically independent but I understand that as upstream you have
certain expectations towards downstream packages.
