### ISSUE TITLE
wapm install -g

### ISSUE THREAD

**Issue by jwulf** [wasmerio/wapm-cli#60]
### Motivation

I want to be able to use lolcat all the time, anywhere on my system.

### Proposed solution

Create a `~/.wapm` folder and install packages here with a `-g` flag to the `wapm install` command. Add this directory to the search path of `wasmer run`.

### Alternatives

I've wired it up manually and have to cd into this directory to install globally-available packages.

### Additional context

Screenshot and documented workaround here:
https://dev.to/jwulf/i-can-t-believe-it-s-webassembly-308c

**Comment by azah** [comment]
I think this is a good idea, but before that, wapm needs a versioning tool. basically, `nvm` but called `wvm` or something.

This way, things like permission issues are negated. Unlike npm, `sudo wpm` should never ever need to be a thing.

**Comment by xmclark** [comment]
@azah a versioning tool like `nvm` is a nice idea. It was something I enjoyed using very much in my javascript days. 

We may adopt a dedicated cli command like the `self-update` command seen in [`wasmer`](https://wasmer.io/). A separate tool would help mitigate changes to command interface. 

I will open a new issue that addresses this suggestion.

**Comment by xmclark** [comment]
`wapm-cli` will have global install in our next release!

`> wapm -g lua`
`> wapm run lua`
