### ISSUE TITLE
Allow declaring specific version when installing a package

### ISSUE THREAD

**Issue by andrew** [wasmerio/wapm-cli#63]
### Motivation

I'd like to be able to install a specific version of a package via the command line rather than always getting the latest release

### Proposed solution

My initial thought was to add a --version flag, `wapm install lolcat --version 0.1.1` but when looking into the code I saw that you can pass multiple package names to the install command, so perhaps instead users can optionally specify the version on the end of each package, separated by an @: `wapm install lua lolcat@0.1.1` 

I've not written any rust before but would be happy to take a stab at implementing if this is something that would be accepted.

**Comment by xmclark** [comment]
@andrew thanks for suggesting this! I think this a great feature request. It would be nice to do this. I like the `@` syntax. 

Here are some use cases I see for the install command:
`wapm install`
`wapm install lua@0.1.2`
`wapm install xmclark/rust-example@0.1.1`
`wapm install xmclark/rust-example@0.1.1 lua@0.1.2`

**Comment by andrew** [comment]
@xmclark pull request opened here: https://github.com/wasmerio/wapm-cli/pull/65
