### ISSUE TITLE
Allow specifying a range of acceptable versions for a dependency

### ISSUE THREAD

**Issue by andrew** [wasmerio/wapm-cli#64]
### Motivation

When declaring a dependency in `wapm.toml` you currently have to specify a specific version number, which means every time there's a new release of that dependency, you need to manually update the number and release a new version of your package. As dependency trees get deeper this can cause a lot of release bumps.

### Proposed solution

It'd be great to be able to pass a [semver](https://semver.org) range when declaring a dependency:

```
[dependencies]
"navigaid/wapm" = ">= 0.1.2"
```

https://github.com/steveklabnik/semver has a nice implementation in rust, including support for ranges like: `>= 1.0.0`, `~1.2` and `^0.0.3`

**Comment by xmclark** [comment]
This is an awesome idea! We are discussing a roadmap this morning and I will put this suggestion on it. 

I like it a lot because this is a common and intuitive feature.
