### ISSUE TITLE
Deny warnings and enforce cargo fmt in azure pipelines

### ISSUE THREAD

**Issue by xmclark** [wasmerio/wapm-cli#68]
We should enforce `cargo fmt` and deny warnings in CI! Plenty of projects do this. [Wasmer does this with circle CI](https://github.com/wasmerio/wasmer/blob/master/Makefile#L30), and I'm sure we can figure it out for azure pipelines.

**Comment by andrew** [comment]
Opened a PR to add this: https://github.com/wasmerio/wapm-cli/pull/89
