### ISSUE TITLE
Bin command

### ISSUE THREAD

**Issue by xmclark** [wasmerio/wapm-cli#88]
There was a feature request on another PR: 
https://github.com/wasmerio/wapm-cli/pull/87#issuecomment-487787433

I think it will be useful to add a command to get the bin folder:

```
# outputs the local bin folder
wapm bin

# outputs the global bin folder
wapm bin -g
```

And it permits doing something similar to what is exposed here:
https://yarnpkg.com/en/docs/cli/global

```
export PATH="$(wapm bin -g):$PATH"
```

**Comment by MarkMcCaskey** [comment]
resolved by #91
